"""Sample-from-real: seed the demo pipeline with 1 real issue per family.

Replaces the "normalize from synthetic raw_findings" step in the demo
pipeline. Instead of processing a hand-curated 5-row fixture, we:

  1. Read every issue from public.issues where source ends in '-ec2'
     (i.e. was fetched by the deployed instance's scanner endpoints)
  2. Classify each into one of the 5 remediation families
  3. Pick the highest-risk issue per family (up to 1 per family, 5 total)
  4. Copy the selected issues into demo.issues with a new agent_run_id

Enrichment (Sub-Agent 2 demo) and remediation (Sub-Agent 3 demo) then run
against these copied rows, isolated in the demo schema.

Design notes:
  - When some families have no -ec2 issues, we ship what we have and
    trace which families were missing. Never blocks the demo run.
  - raw_finding_id is preserved from the source row (still points at
    public.raw_findings). Not a functional dep — nothing in the demo
    pipeline reads that FK; it's kept as an audit link.
  - Issue ids are re-generated by the demo.issues sequence so demo/public
    IDs never collide.
"""

from __future__ import annotations

from typing import Any

from ..db import supabase_admin, supabase_admin_demo
from .remediation.classifier import classify_finding
from .trace_demo import emit_trace_demo


FAMILIES = [
    "public_exposure",
    "network_exposure",
    "injection",
    "vulnerable_dependency",
    "os_vulnerability",
]

# Rank severity/priority strings so we can pick the "highest-risk" issue per
# family deterministically even when derived_risk is NULL. Fallback ordering.
_SEVERITY_RANK = {
    "critical": 4, "Critical": 4, "CRITICAL": 4,
    "high": 3, "High": 3, "HIGH": 3,
    "medium": 2, "Medium": 2, "MEDIUM": 2,
    "low": 1, "Low": 1, "LOW": 1,
}


def sample_and_copy_ec2_issues(run_id: str, real_run_id: str | None = None) -> dict:
    """Query public.issues (source LIKE '%-ec2'), classify + group by family,
    copy 1 per family into demo.issues under this run_id.

    Args:
        run_id: the DEMO agent_run to tag copies with.
        real_run_id: if provided, restricts sampling to issues created by
            THIS real fetch (so we don't pull in stale -ec2 rows from prior
            runs). If None, samples across every -ec2 issue in the DB —
            useful when the demo is triggered without a chained real fetch.

    Returns: {"sampled": N, "families_found": [...], "families_missing": [...]}
    """
    sb_pub = supabase_admin()
    sb_demo = supabase_admin_demo()

    # ---- 1. Pull every -ec2 issue from public (optionally scoped by run) ----
    q = sb_pub.table("issues").select("*").like("source", "%-ec2")
    if real_run_id:
        q = q.eq("agent_run_id", real_run_id)
    ec2_issues = q.execute().data or []

    scope_msg = (
        f"scoped to real_run_id={real_run_id[:8]}…" if real_run_id else "across ALL -ec2 issues"
    )
    emit_trace_demo(
        run_id,
        "system",
        "MESSAGE",
        f"Found {len(ec2_issues)} issue(s) with source suffix '-ec2' ({scope_msg})",
    )

    if not ec2_issues:
        emit_trace_demo(
            run_id,
            "system",
            "MESSAGE",
            "No -ec2 issues to sample. Run 'Fetch findings' for an -ec2 scanner first.",
        )
        return {"sampled": 0, "families_found": [], "families_missing": FAMILIES}

    # ---- 2. Batch-fetch raw_findings for deterministic classification ----
    # Some scanners (notably Checkov) produce normalized issues whose title
    # is just the check_id (e.g. "CKV_AWS_24"). The classifier reads raw.resource
    # to derive family reliably. One indexed IN query for the batch.
    raw_by_id: dict[int, dict] = {}
    raw_ids = [i["raw_finding_id"] for i in ec2_issues if i.get("raw_finding_id") is not None]
    if raw_ids:
        raw_rows = (
            sb_pub.table("raw_findings")
            .select("id, raw")
            .in_("id", raw_ids)
            .execute()
            .data
            or []
        )
        raw_by_id = {r["id"]: (r.get("raw") or {}) for r in raw_rows}

    # ---- 3. Classify each into a family ----
    by_family: dict[str, list[dict]] = {f: [] for f in FAMILIES}
    unknown_count = 0
    for iss in ec2_issues:
        raw = raw_by_id.get(iss.get("raw_finding_id"))
        fam = classify_finding(iss, raw=raw)
        if fam in by_family:
            by_family[fam].append(iss)
        else:
            unknown_count += 1

    family_counts = {f: len(issues) for f, issues in by_family.items()}
    emit_trace_demo(
        run_id,
        "system",
        "MESSAGE",
        f"Family breakdown: {family_counts}"
        + (f" (plus {unknown_count} unclassified)" if unknown_count else ""),
    )

    # ---- 3. Pick 1 per family (highest derived_risk, tie-break by severity) ----
    def _rank(issue: dict) -> tuple[float, int]:
        risk = issue.get("derived_risk")
        risk_val = float(risk) if risk is not None else -1.0
        sev_val = _SEVERITY_RANK.get(issue.get("severity") or "", 0)
        return (risk_val, sev_val)

    picks: list[dict] = []
    families_missing: list[str] = []
    for fam in FAMILIES:
        candidates = by_family[fam]
        if not candidates:
            families_missing.append(fam)
            continue
        picks.append(max(candidates, key=_rank))

    if families_missing:
        emit_trace_demo(
            run_id,
            "system",
            "MESSAGE",
            f"Sampled {len(picks)}/5 families. Missing: {families_missing}",
        )
    else:
        emit_trace_demo(
            run_id,
            "system",
            "MESSAGE",
            f"Sampled {len(picks)}/5 families — all covered",
        )

    if not picks:
        return {"sampled": 0, "families_found": [], "families_missing": FAMILIES}

    # ---- 4. Copy picks into demo.issues under this run_id ----
    # Strip the primary key + timestamps so the demo sequence assigns fresh
    # values. Everything else preserves the real issue's shape.
    to_insert: list[dict] = []
    for iss in picks:
        row = {k: v for k, v in iss.items() if k not in ("id", "created_at", "updated_at")}
        row["agent_run_id"] = run_id
        to_insert.append(row)

    inserted = sb_demo.table("issues").insert(to_insert).execute()
    inserted_count = len(inserted.data or [])

    emit_trace_demo(
        run_id,
        "system",
        "DONE",
        f"SAMPLE_DONE — copied {inserted_count} real -ec2 issue(s) into demo.issues",
        payload={
            "from": "sample",
            "status": "SAMPLE_DONE",
            "scan_id": run_id,
            "sampled": inserted_count,
            "families_found": [f for f in FAMILIES if f not in families_missing],
            "families_missing": families_missing,
        },
    )

    return {
        "sampled": inserted_count,
        "families_found": [f for f in FAMILIES if f not in families_missing],
        "families_missing": families_missing,
    }
