"""Sample-from-real: seed the demo pipeline with 1 real issue per family.

Replaces the "normalize from synthetic raw_findings" step in the demo
pipeline. Instead of processing a hand-curated 5-row fixture, we:

  1. Read every issue from public.issues where source ends in '-ec2'
     (i.e. was fetched by the deployed instance's scanner endpoints)
  2. Classify each into one of the 5 remediation families
  3. Pick the highest-risk issue per family (up to 1 per family, 5 total)
  4. Copy the selected issues into demo.issues with a new agent_run_id

Enrichment (Sub-Agent 2 demo) and remediation (Sub-Agent 3 demo) then run
against these copied rows, isolated in the demo schema.

Design notes:
  - When some families have no -ec2 issues, we ship what we have and
    trace which families were missing. Never blocks the demo run.
  - raw_finding_id is preserved from the source row (still points at
    public.raw_findings). Not a functional dep — nothing in the demo
    pipeline reads that FK; it's kept as an audit link.
  - Issue ids are re-generated by the demo.issues sequence so demo/public
    IDs never collide.
"""

from __future__ import annotations

from ..db import supabase_admin, supabase_admin_demo
from .remediation.classifier import classify_finding
from .trace_demo import emit_trace_demo


FAMILIES = [
    "public_exposure",
    "network_exposure",
    "injection",
    "vulnerable_dependency",
    "os_vulnerability",
]


# Pinned demo issues — identified by (source_vuln_id, asset_identity.resource).
# Row IDs drift across real-fetch runs (each fetch creates fresh rows), but
# these two fields are stable identifiers for "the same finding on the same
# resource". Sampler prefers pinned when present; falls back to
# highest-risk-per-family when a pinned check has no matching row this run.
#
# Curated to give the demo pipeline a stable, reproducible set that exercises
# the closed loop across a range of remediation shapes:
#   * CKV_AWS_21, CKV2_AWS_6, CKV_AWS_18 — additive IaC edits (add a
#     resource); the S3 bucket ends up with versioning, BPA, and access
#     logging all successfully declared in main.tf.
#   * CKV_AWS_24 — sed-mutation of an existing SG rule (harder shape; often
#     rolls back cleanly).
#   * CKV2_AWS_5 — orphan-SG check that SA3 misdiagnoses (adds a rule when
#     the check requires the SG to be attached to a resource); demonstrated
#     as an honest "rewriter cannot fix" case.
#
# CKV_AWS_145 was previously in this list to exercise the KMS-vs-AES256
# rewriter path, but that check specifically mandates KMS and env2's IAM
# role has zero KMS access — the rewriter correctly falls back to AES256
# encryption (which fixes the vulnerability) but Checkov still fails the
# specific check ID. Swapped for CKV_AWS_18 which is any-encryption
# equivalent from a fix-executability standpoint.
_PINNED_DEMO_CHECKS: list[tuple[str, str]] = [
    ("CKV_AWS_21", "aws_s3_bucket.vulnerable_bucket"),  # S3 versioning
    ("CKV2_AWS_6", "aws_s3_bucket.vulnerable_bucket"),  # S3 public access block
    ("CKV_AWS_18", "aws_s3_bucket.vulnerable_bucket"),  # S3 access logging enabled
    ("CKV_AWS_24", "aws_security_group.vulnerable_sg"),  # SG ingress 0.0.0.0/0:22
    # ("CKV2_AWS_5", "aws_security_group.vulnerable_sg"),  # SG must be attached
]


# Per-source "scoops" — take top N highest-risk issues from a source
# regardless of what's in the pinned list. Lets us bring new scanner
# categories into the demo without needing to hand-curate their check IDs.
#
# Ordering: applied AFTER pinned picks, so pinned Checkov issues always
# land first, then the scoop fills in additional findings from other sources.
#
# Each entry: source (matches issues.source exactly) → N issues to pick.
_SOURCE_SCOOPS: dict[str, int] = {
    "checkov-ec2": 20,  # IaC misconfigurations (env2 focus — pinned picks land first, scoop fills to 20)
    "trivy-image-ec2": 20,  # container image OS-package CVEs
    "trivy-image-java-ec2": 4,  # Java image CVEs
    "trivy-image-python-ec2": 4,  # Python image CVEs
    "trivy-os-ec2": 20,  # host-level OS CVEs (Ubuntu/Debian on env2)
    "trivy-os-al2-ec2": 4,  # Amazon Linux 2 host CVEs
    # "trivy-fs-ec2": 4,     # app-level dep CVEs (needs DependencyStrategy)
    "semgrep-ec2": 20,  # SAST findings (needs CodeEditStrategy)
}

# Hard cap on final sample size — trims picks after pinned + scoops + fallback.
# Guarantees the downstream planner never sees more than N issues per demo run.
_MAX_SAMPLE_SIZE = 20


def _resource_label(issue: dict) -> str:
    """Extract the HCL-style resource label from an issue's asset_identity."""
    ai = issue.get("asset_identity") or {}
    return ai.get("resource") or ai.get("file") or ai.get("id") or ""


# Rank severity/priority strings so we can pick the "highest-risk" issue per
# family deterministically even when derived_risk is NULL. Fallback ordering.
_SEVERITY_RANK = {
    "critical": 4,
    "Critical": 4,
    "CRITICAL": 4,
    "high": 3,
    "High": 3,
    "HIGH": 3,
    "medium": 2,
    "Medium": 2,
    "MEDIUM": 2,
    "low": 1,
    "Low": 1,
    "LOW": 1,
}


def sample_and_copy_ec2_issues(run_id: str, real_run_id: str | None = None) -> dict:
    """Query public.issues (source LIKE '%-ec2'), classify + group by family,
    copy 1 per family into demo.issues under this run_id.

    Args:
        run_id: the DEMO agent_run to tag copies with.
        real_run_id: if provided, restricts sampling to issues created by
            THIS real fetch (so we don't pull in stale -ec2 rows from prior
            runs). If None, samples across every -ec2 issue in the DB —
            useful when the demo is triggered without a chained real fetch.

    Returns: {"sampled": N, "families_found": [...], "families_missing": [...]}
    """
    sb_pub = supabase_admin()
    sb_demo = supabase_admin_demo()

    # ---- 1. Pull every -ec2 issue from public (optionally scoped by run) ----
    q = sb_pub.table("issues").select("*").like("source", "%-ec2")
    if real_run_id:
        q = q.eq("agent_run_id", real_run_id)
    ec2_issues = q.execute().data or []

    scope_msg = (
        f"scoped to real_run_id={real_run_id[:8]}…" if real_run_id else "across ALL -ec2 issues"
    )
    emit_trace_demo(
        run_id,
        "system",
        "MESSAGE",
        f"Found {len(ec2_issues)} issue(s) with source suffix '-ec2' ({scope_msg})",
    )

    if not ec2_issues:
        emit_trace_demo(
            run_id,
            "system",
            "MESSAGE",
            "No -ec2 issues to sample. Run 'Fetch findings' for an -ec2 scanner first.",
        )
        return {"sampled": 0, "families_found": [], "families_missing": FAMILIES}

    # ---- 2. Batch-fetch raw_findings for deterministic classification ----
    # Some scanners (notably Checkov) produce normalized issues whose title
    # is just the check_id (e.g. "CKV_AWS_24"). The classifier reads raw.resource
    # to derive family reliably. One indexed IN query for the batch.
    raw_by_id: dict[int, dict] = {}
    raw_ids = [i["raw_finding_id"] for i in ec2_issues if i.get("raw_finding_id") is not None]
    if raw_ids:
        raw_rows = (
            sb_pub.table("raw_findings").select("id, raw").in_("id", raw_ids).execute().data or []
        )
        raw_by_id = {r["id"]: (r.get("raw") or {}) for r in raw_rows}

    # ---- 3. Classify each into a family ----
    by_family: dict[str, list[dict]] = {f: [] for f in FAMILIES}
    unknown_count = 0
    for iss in ec2_issues:
        raw = raw_by_id.get(iss.get("raw_finding_id"))
        fam = classify_finding(iss, raw=raw)
        if fam in by_family:
            by_family[fam].append(iss)
        else:
            unknown_count += 1

    family_counts = {f: len(issues) for f, issues in by_family.items()}
    emit_trace_demo(
        run_id,
        "system",
        "MESSAGE",
        f"Family breakdown: {family_counts}"
        + (f" (plus {unknown_count} unclassified)" if unknown_count else ""),
    )

    # ---- 3. Pick issues ----
    # Preferred path: index all -ec2 issues by (source_vuln_id, resource_label)
    # and look up each pinned check. This makes demo runs reproducible — the
    # same 5 findings feed the pipeline every time regardless of how many
    # times real-fetch has been re-run (which creates fresh row IDs each time).
    #
    # Fallback path: if a pinned check has no matching row this run (fresh
    # env2 doesn't have that scanner registered yet, etc.), we fill missing
    # families from the highest-risk-per-family pool so the pipeline still
    # has SOMETHING to work with rather than exiting empty.
    def _rank(issue: dict) -> tuple[float, int]:
        risk = issue.get("derived_risk")
        risk_val = float(risk) if risk is not None else -1.0
        sev_val = _SEVERITY_RANK.get(issue.get("severity") or "", 0)
        return (risk_val, sev_val)

    by_pin: dict[tuple[str, str], dict] = {}
    for iss in ec2_issues:
        key = (iss.get("source_vuln_id") or "", _resource_label(iss))
        # First-seen wins — real-fetch may create duplicate rows across runs.
        by_pin.setdefault(key, iss)

    picks: list[dict] = []
    pinned_hits: list[str] = []
    pinned_misses: list[str] = []
    for check_id, resource in _PINNED_DEMO_CHECKS:
        hit = by_pin.get((check_id, resource))
        if hit is not None:
            picks.append(hit)
            pinned_hits.append(f"{check_id}@{resource.split('.')[-1]}")
        else:
            pinned_misses.append(f"{check_id}@{resource.split('.')[-1]}")

    emit_trace_demo(
        run_id,
        "system",
        "MESSAGE",
        f"Pinned picks: {len(picks)}/{len(_PINNED_DEMO_CHECKS)} hit "
        f"(hit={pinned_hits or '-'}, missed={pinned_misses or '-'})",
    )

    # Per-source scoops — pull top N highest-risk issues from each configured
    # source. Runs AFTER pinned picks so those always land first. Any issue
    # already selected by the pinned pass is skipped.
    #
    # Dedup key: (source_vuln_id, resource_label, line_hint). The line hint
    # collapses TRUE duplicates (same rule + same file + same line) while
    # keeping legitimately distinct findings (same rule triggered on multiple
    # lines of the same file). Universal — line is derived generically from
    # whatever field each scanner emits (semgrep start.line, checkov
    # file_line_range[0], bandit line_number). Without a line hint (rare —
    # some scanners don't emit one), we fall back to the old key.
    def _line_hint(iss: dict) -> str:
        raw = raw_by_id.get(iss.get("raw_finding_id")) or {}
        # Semgrep emits flat `start_line` (int). Some semgrep versions also
        # use nested `start.line`. Check both shapes for portability.
        sl = raw.get("start_line")
        if sl is not None:
            return f"L{sl}"
        start = raw.get("start")
        if isinstance(start, dict) and "line" in start:
            return f"L{start['line']}"  # semgrep (nested form)
        flr = raw.get("file_line_range")
        if isinstance(flr, (list, tuple)) and flr:
            return f"L{flr[0]}"  # checkov
        ln = raw.get("line_number")
        if ln is not None:
            return f"L{ln}"  # bandit
        return ""  # no line info → dedup key stays as (rule, file)

    def _dedup_key(iss: dict) -> tuple[str, str, str]:
        return (iss.get("source_vuln_id") or "", _resource_label(iss), _line_hint(iss))

    already_picked_keys = {_dedup_key(p) for p in picks}
    by_source: dict[str, list[dict]] = {}
    for iss in ec2_issues:
        by_source.setdefault(iss.get("source") or "", []).append(iss)

    for source_name, n in _SOURCE_SCOOPS.items():
        pool = by_source.get(source_name, [])
        if not pool:
            emit_trace_demo(
                run_id,
                "system",
                "MESSAGE",
                f"Scoop skipped: no issues found for source={source_name!r}",
            )
            continue

        # Sort by (derived_risk DESC, severity_rank DESC) — same ordering
        # the fallback path already uses.
        pool_sorted = sorted(pool, key=_rank, reverse=True)

        scooped_this_source = 0
        for iss in pool_sorted:
            if scooped_this_source >= n:
                break
            key = _dedup_key(iss)
            if key in already_picked_keys:
                continue
            picks.append(iss)
            already_picked_keys.add(key)
            scooped_this_source += 1

        emit_trace_demo(
            run_id,
            "system",
            "MESSAGE",
            f"Scoop {source_name}: picked {scooped_this_source}/{n} (pool={len(pool)} available)",
        )

    # Fallback: if pinned picks < 2, top up from families that weren't
    # covered by any pinned hit. Preserves the demo running on fresh env2
    # setups where pinned checks may not exist yet.
    if len(picks) < 2:
        covered_families = {
            classify_finding(p, raw=raw_by_id.get(p.get("raw_finding_id"))) for p in picks
        }
        for fam in FAMILIES:
            if fam in covered_families:
                continue
            candidates = by_family[fam]
            if not candidates:
                continue
            fallback_pick = max(candidates, key=_rank)
            picks.append(fallback_pick)
            emit_trace_demo(
                run_id,
                "system",
                "MESSAGE",
                f"⚠ Fallback: pinned set insufficient — added highest-risk {fam} "
                f"issue (source_vuln_id={fallback_pick.get('source_vuln_id')})",
            )

    # (per-file dedup removed 2026-08-21 — replaced by per-file batching in
    # planner_demo.run_demo_remediation. Batching groups multiple findings
    # for the same file into ONE package so state drift is impossible AND
    # we still fix every vuln. See the "group by file" step downstream.)

    # Hard cap — trim final sample so the downstream planner + fixer never
    # see more than _MAX_SAMPLE_SIZE issues. Pinned picks + higher-risk
    # scoops land first, so the trimmed set stays representative.
    if len(picks) > _MAX_SAMPLE_SIZE:
        dropped = len(picks) - _MAX_SAMPLE_SIZE
        picks = picks[:_MAX_SAMPLE_SIZE]
        emit_trace_demo(
            run_id,
            "system",
            "MESSAGE",
            f"Cap applied: trimmed to {_MAX_SAMPLE_SIZE} issue(s) (dropped {dropped} lower-priority pick(s))",
        )

    families_missing = [
        f
        for f in FAMILIES
        if f not in {classify_finding(p, raw=raw_by_id.get(p.get("raw_finding_id"))) for p in picks}
    ]

    emit_trace_demo(
        run_id,
        "system",
        "MESSAGE",
        f"Final sample: {len(picks)} issue(s) across "
        f"{len(FAMILIES) - len(families_missing)}/{len(FAMILIES)} families"
        + (f" (families uncovered: {families_missing})" if families_missing else ""),
    )

    if not picks:
        return {"sampled": 0, "families_found": [], "families_missing": FAMILIES}

    # ---- 4. Copy picks into demo.issues under this run_id ----
    # Strip the primary key + timestamps so the demo sequence assigns fresh
    # values. Everything else preserves the real issue's shape.
    to_insert: list[dict] = []
    for iss in picks:
        row = {k: v for k, v in iss.items() if k not in ("id", "created_at", "updated_at")}
        row["agent_run_id"] = run_id
        to_insert.append(row)

    inserted = sb_demo.table("issues").insert(to_insert).execute()
    inserted_count = len(inserted.data or [])

    emit_trace_demo(
        run_id,
        "system",
        "DONE",
        f"SAMPLE_DONE — copied {inserted_count} real -ec2 issue(s) into demo.issues",
        payload={
            "from": "sample",
            "status": "SAMPLE_DONE",
            "scan_id": run_id,
            "sampled": inserted_count,
            "families_found": [f for f in FAMILIES if f not in families_missing],
            "families_missing": families_missing,
        },
    )

    return {
        "sampled": inserted_count,
        "families_found": [f for f in FAMILIES if f not in families_missing],
        "families_missing": families_missing,
    }
