# =============================================================================
# CSPM Lab — Reference Copy (Intentionally Misconfigured Terraform)
# =============================================================================
# This is the REFERENCE copy of the CSPM lab Terraform code.
# The actual applied version lives on the EC2 instances at /opt/vuln-labs/cspm-lab/
# and is generated by user-data.sh.tpl with environment-specific values.
#
# This file is excluded from the workflow Checkov scan (--skip-path vuln-samples).
#
# Intentional findings (2):
#   1. S3 bucket — no encryption, no versioning, no public access block
#   2. Security group — SSH open to the world (0.0.0.0/0)
# =============================================================================

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  backend "s3" {}
}

provider "aws" {
  region = "us-east-1"
}

data "aws_vpc" "default" {
  default = true
}

# -----------------------------------------------------------------------------
# FINDING 1: S3 Bucket — intentionally misconfigured
# -----------------------------------------------------------------------------

resource "aws_s3_bucket" "vulnerable_bucket" {
  bucket        = "cspm-lab-ENVNAME-bucket"
  force_destroy = true

  tags = {
    Name    = "cspm-lab-ENVNAME-bucket"
    Purpose = "checkov-scan-target"
  }
}

# Intentionally NO aws_s3_bucket_server_side_encryption_configuration
# Intentionally NO aws_s3_bucket_versioning
# Intentionally NO aws_s3_bucket_public_access_block
# Intentionally NO aws_s3_bucket_logging

# -----------------------------------------------------------------------------
# FINDING 2: Security Group — SSH open to the world
# -----------------------------------------------------------------------------

resource "aws_security_group" "vulnerable_sg" {
  name        = "cspm-lab-ENVNAME-open-sg"
  description = "INTENTIONALLY OPEN — Checkov scan target"
  vpc_id      = data.aws_vpc.default.id

  ingress {
    description = "SSH open to world — intentional misconfiguration"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name    = "cspm-lab-ENVNAME-open-sg"
    Purpose = "checkov-scan-target"
  }
}
